spring.application.name=epsel-api

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bd_epsel
spring.datasource.username=root
spring.datasource.password=123456

# Configuración de JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=tyn/+TalMOhUSnaMl/gMXXw9Iiu06mC2X8xXw4CvoZDVv+gahHRclRh7uDzPvyXHH8IShlLiuXfpbygWWKni5w==
jwt.expiration=86400000

# Configuración de OCR
ocr.url: http://127.0.0.1:8000/ocr/read